sudo: required

services:
  - docker

install:
  - sudo bash -c "$(curl -fsSL https://s3.amazonaws.com/tools.nanobox.io/bootstrap/ci.sh)"
  - nanobox run -v cp .env.nanobox .env
  - nanobox run -v php artisan key:generate || ( xit=$? && [ $xit -eq 129 ] && true || exit $xit )
  - nanobox run -v php artisan migrate --force --seed || ( xit=$? && [ $xit -eq 129 ] && true || exit $xit )

script:
  - nanobox run -v phpunit -v || ( xit=$? && [ $xit -eq 129 ] && true || exit $xit )

after_failure:
  - cat storage/logs/laravel.log
