#!/bin/bash -e

php artisan migrate
[ -e /data/etc/php.d/xdebug.ini ] || ln -s /app/xdebug.ini /data/etc/php.d/
php artisan queue:listen --queue=default --tries=15 --delay=15 --timeout 3600 &
php-server
jobs -x kill %+
